map_server:
    ros__parameters:
        frame_id: map   
        topic_name: map
        use_sim_time: false
        yaml_filename: "/home/krawus/Studies/MAPR/lab2/ros2_ws/src/example_maps/maps/map_home.yaml"
